### ISSUE TITLE
error when parse uploaded pcap file

### ISSUE THREAD

**Issue by mcxiaoke** [Crepe-Inc/Iridium#5]
when using http://localhost:1984/index.html upload WireShark save pcap file.

stacktrace:

```
> iridium@1.2.1 main
> node . main

[  ▶  ]  <Excel> Loading Excels...
         <Excel> 549/620 excels are loaded into memory.
         <Excel> ID lookup is now enabled. Select text and press Enter or use q(id) in console.
(node:16804) [DEP0128] DeprecationWarning: Invalid 'main' field in 'E:\github\Iridium\node_modules\node-kcp\package.json' of 'node-kcp.node'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
[  ▶  ]  <Dispatch> HTTP: localhost:80
[  ▶  ]  <Dispatch> HTTPS: localhost:443
[  ▶  ]  <Frontend> Frontend running on http://localhost:1984/index.html
         <Frontend> [ConnectReq]
         <Frontend> [ProcessFileReq] [object Object]
Exiting cleanly...
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: unknown magic number: 4d3cb2a1
    at Parser.parseGlobalHeader [as state] (E:\github\Iridium\node_modules\pcap-parser\lib\pcap-parser.js:55:26)
    at Parser.onData (E:\github\Iridium\node_modules\pcap-parser\lib\pcap-parser.js:22:21)
    at Readable.emit (node:events:527:28)
    at Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1011:34)
    at resume_ (node:internal/streams/readable:992:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Parser instance at:
    at Parser.parseGlobalHeader [as state] (E:\github\Iridium\node_modules\pcap-parser\lib\pcap-parser.js:55:12)
    at Parser.onData (E:\github\Iridium\node_modules\pcap-parser\lib\pcap-parser.js:22:21)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

version:
commit be3b68a47d7e8fe870c400121f8a1060274fc6eb (HEAD -> main, origin/main, origin/HEAD)
Author: TheLostTree <65834918+TheLostTree@users.noreply.github.com>
Date:   Sun Apr 24 21:26:46 2022 -0700

    newer cur + option to dump some packets to jsons (in config.js)

**Comment by memetrollsXD** [comment]
Is there a possibility that the pcap may be damaged? Have you tried with different pcaps?

**Comment by mcxiaoke** [comment]
sorry, because i choosed wrong export pcap format.
